### ISSUE TITLE
🚀 [Feature] : Another field for languagecompetencies you do not plan on learning or practicing

### ISSUE THREAD

**Issue by Sultana-Eve** [languageXchange/languageXchange#492] opened 2024-02-21 11:09 UTC
**Is your feature request related to a problem? Please describe.**
i have different levels on different languages i actually have but do not want to improve, but no area to mention them

**Describe the solution you'd like**
a third field of language competences in general

**Describe alternatives you've considered**
mentioning it in learning and practicing would be wrong and speaking at home is simply false xD

**Additional context**
Maybe people can still ask you for those languages aswell

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by behics** [comment] 2024-02-21 15:25
Duplicate of #438

**Closed by behics** 2024-02-21 15:25 UTC
Labels: duplicate, feature
